[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "gpapi_python"
version = "0.1.0"
description = "Python bindings for Google Play API"
requires-python = ">=3.12"