name: Build Linux wheels

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    name: Build wheels on Linux
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          working-directory: ./gpapi-python
          args: --release --sdist -i python3.12 --features pyo3/extension-module
          manylinux: auto
          before-script-linux: |
            yum install -y openssl-devel pkgconfig

      - name: Debug wheel paths
        run: |
          find . -name "*.whl" -o -name "*.tar.gz"

      - name: Upload wheels to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: "**/*.whl"

      - name: Create/Update latest tag
        if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git tag -d latest || true
          git push origin :refs/tags/latest || true

          git tag -a latest -m "Latest release"
          git push origin latest

      - name: Release with latest tag
        if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: "**/*.whl"
          tag_name: latest
          name: "Latest Release"
          body: "This is an automatic release containing the latest wheels."
          prerelease: false
