name: Build Linux wheels

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    name: Build wheels on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          working-directory: ./gpapi-python
          args: --release --sdist -i python3.12 --features pyo3/extension-module
          manylinux: auto

      - name: Upload wheels to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: ./gpapi-python/target/wheels/

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./gpapi-python/target/wheels/*
