name: Build Linux wheels

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    name: Build wheels on Linux
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          working-directory: ./gpapi-python
          args: --release --sdist -i python3.13 -i python3.13 -i python3.13 -i python3.12 -i python3.12 -i python3.12 -i python3.12 -i python3.12 -i python3.12 -i python3.12 -i python3.12 -i python3.12 -i python3.12 -i python3.9 -i python3.9 -i python3.9 -i python3.9 -i python3.9 -i python3.9 -i python3.9 -i python3.9 -i python3.9 -i python3.9 -i python3.9 -i python3.9 -i python3.9 -i python3.9 -i python3.9 -i python3.9 -i python3.9 -i python3.9 -i python3.9 -i python3.9 -i python3.9 -i python3.9 -i python3.8 -i python3.8 -i python3.8 -i python3.8 -i python3.8 -i python3.8 -i python3.8 -i python3.8 -i python3.8 -i python3.8 -i python3.8 -i python3.8 -i python3.8 -i python3.8 -i python3.8 -i python3.8 -i python3.8 -i python3.8 -i python3.8 -i python3.7 -i python3.7 -i python3.7 -i python3.7 -i python3.7 -i python3.7 -i python3.7 -i python3.7 -i python3.7 -i python3.7 -i python3.7 -i python3.7 -i python3.7 -i python3.7 -i python3.7 -i python3.7 -i python3.7 -i python3.6 -i python3.6 -i python3.6 -i python3.6 -i python3.6 -i python3.6 -i python3.6 -i python3.6 -i python3.6 -i python3.5 -i python3.5 -i python3.5 -i python3.4 -i python3.4 -i python3.3 -i python3.3 -i python3.2 --features pyo3/extension-module
          manylinux: auto
          before-script-linux: |
            yum install -y openssl-devel pkgconfig

      - name: Debug wheel paths
        run: |
          find . -name "*.whl" -o -name "*.tar.gz"

      - name: Upload wheels to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: "**/*.whl"

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "**/*.whl"
